/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Name of package */
#define PACKAGE "mfstool"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "alejandro_liu@hotmail.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "mfstool"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "mfstool 0.5"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "mfstool"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.5"

/* Version number of package */
#define VERSION "0.5"
